2022-04-17 22:15:05,822 INFO    MainThread:26788 [wandb_setup.py:_flush():75] Loading settings from C:\Users\12500\.config\wandb\settings
2022-04-17 22:15:05,822 INFO    MainThread:26788 [wandb_setup.py:_flush():75] Loading settings from C:\Projects\Pytorch\Pytorch-UNet-master - 副本\wandb\settings
2022-04-17 22:15:05,822 INFO    MainThread:26788 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-17 22:15:05,822 INFO    MainThread:26788 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'train - 副本.py', 'program': 'C:/Projects/Pytorch/Pytorch-UNet-master - 副本/train - 副本.py'}
2022-04-17 22:15:05,822 INFO    MainThread:26788 [wandb_setup.py:_flush():75] Applying login settings: {'anonymous': 'must'}
2022-04-17 22:15:05,824 INFO    MainThread:26788 [wandb_init.py:_log_setup():405] Logging user logs to C:\Projects\Pytorch\Pytorch-UNet-master - 副本\wandb\run-20220417_221505-36r0bsvm\logs\debug.log
2022-04-17 22:15:05,824 INFO    MainThread:26788 [wandb_init.py:_log_setup():406] Logging internal logs to C:\Projects\Pytorch\Pytorch-UNet-master - 副本\wandb\run-20220417_221505-36r0bsvm\logs\debug-internal.log
2022-04-17 22:15:05,824 INFO    MainThread:26788 [wandb_init.py:init():439] calling init triggers
2022-04-17 22:15:05,824 INFO    MainThread:26788 [wandb_init.py:init():443] wandb.init called with sweep_config: {}
config: {}
2022-04-17 22:15:05,824 INFO    MainThread:26788 [wandb_init.py:init():492] starting backend
2022-04-17 22:15:05,825 INFO    MainThread:26788 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2022-04-17 22:15:05,829 INFO    MainThread:26788 [backend.py:ensure_launched():219] starting backend process...
2022-04-17 22:15:05,914 INFO    MainThread:26788 [backend.py:ensure_launched():225] started backend process with pid: 26512
2022-04-17 22:15:05,915 INFO    MainThread:26788 [wandb_init.py:init():501] backend started and connected
2022-04-17 22:15:05,916 INFO    MainThread:26788 [wandb_init.py:init():565] updated telemetry
2022-04-17 22:15:05,916 INFO    MainThread:26788 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-17 22:15:18,017 WARNING MainThread:26788 [wandb_init.py:init():975] interrupted
Traceback (most recent call last):
  File "C:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 954, in init
    run = wi.init()
  File "C:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 597, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\interface\interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 320, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Anaconda\envs\pytorch\lib\site-packages\wandb\sdk\interface\router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Anaconda\envs\pytorch\lib\threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Anaconda\envs\pytorch\lib\threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
